<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Operations;

use Spaire\Models\Components;
use Spaire\Utils\SpeakeasyMetadata;
class BenefitsUpdateRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Spaire\Models\Components\BenefitCustomUpdate|\Spaire\Models\Components\BenefitDiscordUpdate|\Spaire\Models\Components\BenefitGitHubRepositoryUpdate|\Spaire\Models\Components\BenefitDownloadablesUpdate|\Spaire\Models\Components\BenefitLicenseKeysUpdate|\Spaire\Models\Components\BenefitMeterCreditUpdate $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\BenefitCustomUpdate|Components\BenefitDiscordUpdate|Components\BenefitGitHubRepositoryUpdate|Components\BenefitDownloadablesUpdate|Components\BenefitLicenseKeysUpdate|Components\BenefitMeterCreditUpdate $requestBody;

    /**
     * @param  string  $id
     * @param  \Spaire\Models\Components\BenefitCustomUpdate|\Spaire\Models\Components\BenefitDiscordUpdate|\Spaire\Models\Components\BenefitGitHubRepositoryUpdate|\Spaire\Models\Components\BenefitDownloadablesUpdate|\Spaire\Models\Components\BenefitLicenseKeysUpdate|\Spaire\Models\Components\BenefitMeterCreditUpdate  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $id, Components\BenefitCustomUpdate|Components\BenefitDiscordUpdate|Components\BenefitGitHubRepositoryUpdate|Components\BenefitDownloadablesUpdate|Components\BenefitLicenseKeysUpdate|Components\BenefitMeterCreditUpdate $requestBody)
    {
        $this->id = $id;
        $this->requestBody = $requestBody;
    }
}