<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Operations;

use Spaire\Models\Components;
use Spaire\Utils\SpeakeasyMetadata;
class CheckoutsUpdateRequest
{
    /**
     * The checkout session ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var Components\CheckoutUpdate $checkoutUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CheckoutUpdate $checkoutUpdate;

    /**
     * @param  string  $id
     * @param  Components\CheckoutUpdate  $checkoutUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\CheckoutUpdate $checkoutUpdate)
    {
        $this->id = $id;
        $this->checkoutUpdate = $checkoutUpdate;
    }
}