<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Operations;

use Spaire\Utils\SpeakeasyMetadata;
class CustomerPortalOrganizationsGetRequest
{
    /**
     * The organization slug.
     *
     * @var string $slug
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=slug')]
    public string $slug;

    /**
     * @param  string  $slug
     * @phpstan-pure
     */
    public function __construct(string $slug)
    {
        $this->slug = $slug;
    }
}