<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Operations;

use Spaire\Models\Components;
use Spaire\Utils\SpeakeasyMetadata;
class CustomerPortalMembersUpdateMemberRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var Components\CustomerPortalMemberUpdate $customerPortalMemberUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomerPortalMemberUpdate $customerPortalMemberUpdate;

    /**
     * @param  string  $id
     * @param  Components\CustomerPortalMemberUpdate  $customerPortalMemberUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\CustomerPortalMemberUpdate $customerPortalMemberUpdate)
    {
        $this->id = $id;
        $this->customerPortalMemberUpdate = $customerPortalMemberUpdate;
    }
}