<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Operations;

use Spaire\Models\Components;
use Spaire\Utils\SpeakeasyMetadata;
class CustomFieldsUpdateRequest
{
    /**
     * The custom field ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Spaire\Models\Components\CustomFieldUpdateText|\Spaire\Models\Components\CustomFieldUpdateNumber|\Spaire\Models\Components\CustomFieldUpdateDate|\Spaire\Models\Components\CustomFieldUpdateCheckbox|\Spaire\Models\Components\CustomFieldUpdateSelect $customFieldUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomFieldUpdateText|Components\CustomFieldUpdateNumber|Components\CustomFieldUpdateDate|Components\CustomFieldUpdateCheckbox|Components\CustomFieldUpdateSelect $customFieldUpdate;

    /**
     * @param  string  $id
     * @param  \Spaire\Models\Components\CustomFieldUpdateText|\Spaire\Models\Components\CustomFieldUpdateNumber|\Spaire\Models\Components\CustomFieldUpdateDate|\Spaire\Models\Components\CustomFieldUpdateCheckbox|\Spaire\Models\Components\CustomFieldUpdateSelect  $customFieldUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\CustomFieldUpdateText|Components\CustomFieldUpdateNumber|Components\CustomFieldUpdateDate|Components\CustomFieldUpdateCheckbox|Components\CustomFieldUpdateSelect $customFieldUpdate)
    {
        $this->id = $id;
        $this->customFieldUpdate = $customFieldUpdate;
    }
}