<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Operations;

use Spaire\Models\Components;
use Spaire\Utils\SpeakeasyMetadata;
class CustomerPortalBenefitGrantsUpdateRequest
{
    /**
     * The benefit grant ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Spaire\Models\Components\CustomerBenefitGrantDiscordUpdate|\Spaire\Models\Components\CustomerBenefitGrantGitHubRepositoryUpdate|\Spaire\Models\Components\CustomerBenefitGrantDownloadablesUpdate|\Spaire\Models\Components\CustomerBenefitGrantLicenseKeysUpdate|\Spaire\Models\Components\CustomerBenefitGrantCustomUpdate|\Spaire\Models\Components\CustomerBenefitGrantMeterCreditUpdate $customerBenefitGrantUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomerBenefitGrantDiscordUpdate|Components\CustomerBenefitGrantGitHubRepositoryUpdate|Components\CustomerBenefitGrantDownloadablesUpdate|Components\CustomerBenefitGrantLicenseKeysUpdate|Components\CustomerBenefitGrantCustomUpdate|Components\CustomerBenefitGrantMeterCreditUpdate $customerBenefitGrantUpdate;

    /**
     * @param  string  $id
     * @param  \Spaire\Models\Components\CustomerBenefitGrantDiscordUpdate|\Spaire\Models\Components\CustomerBenefitGrantGitHubRepositoryUpdate|\Spaire\Models\Components\CustomerBenefitGrantDownloadablesUpdate|\Spaire\Models\Components\CustomerBenefitGrantLicenseKeysUpdate|\Spaire\Models\Components\CustomerBenefitGrantCustomUpdate|\Spaire\Models\Components\CustomerBenefitGrantMeterCreditUpdate  $customerBenefitGrantUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\CustomerBenefitGrantDiscordUpdate|Components\CustomerBenefitGrantGitHubRepositoryUpdate|Components\CustomerBenefitGrantDownloadablesUpdate|Components\CustomerBenefitGrantLicenseKeysUpdate|Components\CustomerBenefitGrantCustomUpdate|Components\CustomerBenefitGrantMeterCreditUpdate $customerBenefitGrantUpdate)
    {
        $this->id = $id;
        $this->customerBenefitGrantUpdate = $customerBenefitGrantUpdate;
    }
}