<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Operations;

use Spaire\Models\Components;
class EventsGetResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var \Psr\Http\Message\ResponseInterface $rawResponse
     */
    public \Psr\Http\Message\ResponseInterface $rawResponse;

    /**
     * Successful Response
     *
     * @var \Spaire\Models\Components\MeterCreditEvent|\Spaire\Models\Components\MeterResetEvent|\Spaire\Models\Components\BenefitGrantedEvent|\Spaire\Models\Components\BenefitCycledEvent|\Spaire\Models\Components\BenefitUpdatedEvent|\Spaire\Models\Components\BenefitRevokedEvent|\Spaire\Models\Components\SubscriptionCreatedEvent|\Spaire\Models\Components\SubscriptionCycledEvent|\Spaire\Models\Components\SubscriptionCanceledEvent|\Spaire\Models\Components\SubscriptionRevokedEvent|\Spaire\Models\Components\SubscriptionUncanceledEvent|\Spaire\Models\Components\SubscriptionProductUpdatedEvent|\Spaire\Models\Components\SubscriptionSeatsUpdatedEvent|\Spaire\Models\Components\SubscriptionBillingPeriodUpdatedEvent|\Spaire\Models\Components\OrderPaidEvent|\Spaire\Models\Components\OrderRefundedEvent|\Spaire\Models\Components\CheckoutCreatedEvent|\Spaire\Models\Components\CustomerCreatedEvent|\Spaire\Models\Components\CustomerUpdatedEvent|\Spaire\Models\Components\CustomerDeletedEvent|\Spaire\Models\Components\BalanceOrderEvent|\Spaire\Models\Components\BalanceCreditOrderEvent|\Spaire\Models\Components\BalanceRefundEvent|\Spaire\Models\Components\BalanceRefundReversalEvent|\Spaire\Models\Components\BalanceDisputeEvent|\Spaire\Models\Components\BalanceDisputeReversalEvent|\Spaire\Models\Components\UserEvent|null $event
     */
    public Components\MeterCreditEvent|Components\MeterResetEvent|Components\BenefitGrantedEvent|Components\BenefitCycledEvent|Components\BenefitUpdatedEvent|Components\BenefitRevokedEvent|Components\SubscriptionCreatedEvent|Components\SubscriptionCycledEvent|Components\SubscriptionCanceledEvent|Components\SubscriptionRevokedEvent|Components\SubscriptionUncanceledEvent|Components\SubscriptionProductUpdatedEvent|Components\SubscriptionSeatsUpdatedEvent|Components\SubscriptionBillingPeriodUpdatedEvent|Components\OrderPaidEvent|Components\OrderRefundedEvent|Components\CheckoutCreatedEvent|Components\CustomerCreatedEvent|Components\CustomerUpdatedEvent|Components\CustomerDeletedEvent|Components\BalanceOrderEvent|Components\BalanceCreditOrderEvent|Components\BalanceRefundEvent|Components\BalanceRefundReversalEvent|Components\BalanceDisputeEvent|Components\BalanceDisputeReversalEvent|Components\UserEvent|null $event = null;

    /**
     * @param  string  $contentType
     * @param  int  $statusCode
     * @param  \Psr\Http\Message\ResponseInterface  $rawResponse
     * @param  \Spaire\Models\Components\MeterCreditEvent|\Spaire\Models\Components\MeterResetEvent|\Spaire\Models\Components\BenefitGrantedEvent|\Spaire\Models\Components\BenefitCycledEvent|\Spaire\Models\Components\BenefitUpdatedEvent|\Spaire\Models\Components\BenefitRevokedEvent|\Spaire\Models\Components\SubscriptionCreatedEvent|\Spaire\Models\Components\SubscriptionCycledEvent|\Spaire\Models\Components\SubscriptionCanceledEvent|\Spaire\Models\Components\SubscriptionRevokedEvent|\Spaire\Models\Components\SubscriptionUncanceledEvent|\Spaire\Models\Components\SubscriptionProductUpdatedEvent|\Spaire\Models\Components\SubscriptionSeatsUpdatedEvent|\Spaire\Models\Components\SubscriptionBillingPeriodUpdatedEvent|\Spaire\Models\Components\OrderPaidEvent|\Spaire\Models\Components\OrderRefundedEvent|\Spaire\Models\Components\CheckoutCreatedEvent|\Spaire\Models\Components\CustomerCreatedEvent|\Spaire\Models\Components\CustomerUpdatedEvent|\Spaire\Models\Components\CustomerDeletedEvent|\Spaire\Models\Components\BalanceOrderEvent|\Spaire\Models\Components\BalanceCreditOrderEvent|\Spaire\Models\Components\BalanceRefundEvent|\Spaire\Models\Components\BalanceRefundReversalEvent|\Spaire\Models\Components\BalanceDisputeEvent|\Spaire\Models\Components\BalanceDisputeReversalEvent|\Spaire\Models\Components\UserEvent|null  $event
     * @phpstan-pure
     */
    public function __construct(string $contentType, int $statusCode, \Psr\Http\Message\ResponseInterface $rawResponse, Components\MeterCreditEvent|Components\MeterResetEvent|Components\BenefitGrantedEvent|Components\BenefitCycledEvent|Components\BenefitUpdatedEvent|Components\BenefitRevokedEvent|Components\SubscriptionCreatedEvent|Components\SubscriptionCycledEvent|Components\SubscriptionCanceledEvent|Components\SubscriptionRevokedEvent|Components\SubscriptionUncanceledEvent|Components\SubscriptionProductUpdatedEvent|Components\SubscriptionSeatsUpdatedEvent|Components\SubscriptionBillingPeriodUpdatedEvent|Components\OrderPaidEvent|Components\OrderRefundedEvent|Components\CheckoutCreatedEvent|Components\CustomerCreatedEvent|Components\CustomerUpdatedEvent|Components\CustomerDeletedEvent|Components\BalanceOrderEvent|Components\BalanceCreditOrderEvent|Components\BalanceRefundEvent|Components\BalanceRefundReversalEvent|Components\BalanceDisputeEvent|Components\BalanceDisputeReversalEvent|Components\UserEvent|null $event = null)
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->event = $event;
    }
}