<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Operations;

use Spaire\Models\Components;
use Spaire\Utils\SpeakeasyMetadata;
class MembersUpdateMemberRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var Components\MemberUpdate $memberUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\MemberUpdate $memberUpdate;

    /**
     * @param  string  $id
     * @param  Components\MemberUpdate  $memberUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\MemberUpdate $memberUpdate)
    {
        $this->id = $id;
        $this->memberUpdate = $memberUpdate;
    }
}