<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Operations;

use Spaire\Models\Components;
use Spaire\Utils\SpeakeasyMetadata;
class MetersUpdateRequest
{
    /**
     * The meter ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var Components\MeterUpdate $meterUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\MeterUpdate $meterUpdate;

    /**
     * @param  string  $id
     * @param  Components\MeterUpdate  $meterUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\MeterUpdate $meterUpdate)
    {
        $this->id = $id;
        $this->meterUpdate = $meterUpdate;
    }
}