<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Operations;

use Spaire\Utils\SpeakeasyMetadata;
class Oauth2ClientsOauth2GetClientRequest
{
    /**
     *
     * @var string $clientId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=client_id')]
    public string $clientId;

    /**
     * @param  string  $clientId
     * @phpstan-pure
     */
    public function __construct(string $clientId)
    {
        $this->clientId = $clientId;
    }
}