<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Operations;

use Spaire\Models\Components;
use Spaire\Utils\SpeakeasyMetadata;
class Oauth2ClientsOauth2UpdateClientRequest
{
    /**
     *
     * @var string $clientId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=client_id')]
    public string $clientId;

    /**
     *
     * @var Components\OAuth2ClientConfigurationUpdate $oAuth2ClientConfigurationUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\OAuth2ClientConfigurationUpdate $oAuth2ClientConfigurationUpdate;

    /**
     * @param  string  $clientId
     * @param  Components\OAuth2ClientConfigurationUpdate  $oAuth2ClientConfigurationUpdate
     * @phpstan-pure
     */
    public function __construct(string $clientId, Components\OAuth2ClientConfigurationUpdate $oAuth2ClientConfigurationUpdate)
    {
        $this->clientId = $clientId;
        $this->oAuth2ClientConfigurationUpdate = $oAuth2ClientConfigurationUpdate;
    }
}