<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


/** AttachedCustomField - Schema of a custom field attached to a resource. */
class AttachedCustomField
{
    /**
     * ID of the custom field.
     *
     * @var string $customFieldId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_field_id')]
    public string $customFieldId;

    /**
     *
     * @var CustomFieldText|CustomFieldNumber|CustomFieldDate|CustomFieldCheckbox|CustomFieldSelect $customField
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_field')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\CustomFieldText|\Spaire\Models\Components\CustomFieldNumber|\Spaire\Models\Components\CustomFieldDate|\Spaire\Models\Components\CustomFieldCheckbox|\Spaire\Models\Components\CustomFieldSelect')]
    #[\Speakeasy\Serializer\Annotation\UnionDiscriminator(field: 'type', map: ['checkbox' => '\Spaire\Models\Components\CustomFieldCheckbox', 'date' => '\Spaire\Models\Components\CustomFieldDate', 'number' => '\Spaire\Models\Components\CustomFieldNumber', 'select' => '\Spaire\Models\Components\CustomFieldSelect', 'text' => '\Spaire\Models\Components\CustomFieldText'])]
    public CustomFieldText|CustomFieldNumber|CustomFieldDate|CustomFieldCheckbox|CustomFieldSelect $customField;

    /**
     * Order of the custom field in the resource.
     *
     * @var int $order
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('order')]
    public int $order;

    /**
     * Whether the value is required for this custom field.
     *
     * @var bool $required
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('required')]
    public bool $required;

    /**
     * @param  string  $customFieldId
     * @param  CustomFieldText|CustomFieldNumber|CustomFieldDate|CustomFieldCheckbox|CustomFieldSelect  $customField
     * @param  int  $order
     * @param  bool  $required
     * @phpstan-pure
     */
    public function __construct(string $customFieldId, CustomFieldText|CustomFieldNumber|CustomFieldDate|CustomFieldCheckbox|CustomFieldSelect $customField, int $order, bool $required)
    {
        $this->customFieldId = $customFieldId;
        $this->customField = $customField;
        $this->order = $order;
        $this->required = $required;
    }
}