<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


class BenefitLicenseKeyExpirationProperties
{
    /**
     *
     * @var int $ttl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ttl')]
    public int $ttl;

    /**
     *
     * @var \Spaire\Models\Components\Timeframe $timeframe
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timeframe')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\Timeframe')]
    public Timeframe $timeframe;

    /**
     * @param  int  $ttl
     * @param  \Spaire\Models\Components\Timeframe  $timeframe
     * @phpstan-pure
     */
    public function __construct(int $ttl, Timeframe $timeframe)
    {
        $this->ttl = $ttl;
        $this->timeframe = $timeframe;
    }
}