<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


class ClientInvoiceLineItemCreate
{
    /**
     * Line item description shown on the invoice.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Unit price in the smallest currency unit (e.g. cents).
     *
     * @var int $unitAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unit_amount')]
    public int $unitAmount;

    /**
     * Quantity.
     *
     * @var ?int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $quantity = null;

    /**
     * @param  string  $description
     * @param  int  $unitAmount
     * @param  ?int  $quantity
     * @phpstan-pure
     */
    public function __construct(string $description, int $unitAmount, ?int $quantity = 1)
    {
        $this->description = $description;
        $this->unitAmount = $unitAmount;
        $this->quantity = $quantity;
    }
}