<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


/** ClientInvoiceLineItemPreview - Relaxed line item for preview — allows zero amounts for in-progress editing. */
class ClientInvoiceLineItemPreview
{
    /**
     * Line item description.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Quantity.
     *
     * @var ?int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $quantity = null;

    /**
     * Unit price in cents (0 allowed for preview).
     *
     * @var ?int $unitAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unit_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $unitAmount = null;

    /**
     * @param  ?string  $description
     * @param  ?int  $quantity
     * @param  ?int  $unitAmount
     * @phpstan-pure
     */
    public function __construct(?string $description = '—', ?int $quantity = 1, ?int $unitAmount = 0)
    {
        $this->description = $description;
        $this->quantity = $quantity;
        $this->unitAmount = $unitAmount;
    }
}