<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;

use Brick\DateTime\LocalDate;
class ClientInvoiceSchema
{
    /**
     * The ID of the object.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Creation timestamp of the object.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public string $organizationId;

    /**
     *
     * @var string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    public string $customerId;

    /**
     *
     * @var ClientInvoiceStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\ClientInvoiceStatus')]
    public ClientInvoiceStatus $status;

    /**
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     *
     * @var int $subtotalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtotal_amount')]
    public int $subtotalAmount;

    /**
     *
     * @var int $discountAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_amount')]
    public int $discountAmount;

    /**
     *
     * @var int $taxAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_amount')]
    public int $taxAmount;

    /**
     *
     * @var int $totalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total_amount')]
    public int $totalAmount;

    /**
     *
     * @var bool $includePaymentLink
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('include_payment_link')]
    public bool $includePaymentLink;

    /**
     *
     * @var bool $showLogo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('show_logo')]
    public bool $showLogo;

    /**
     *
     * @var bool $showMorAttribution
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('show_mor_attribution')]
    public bool $showMorAttribution;

    /**
     * Last modification timestamp of the object.
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     *
     * @var ?string $stripeInvoiceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('stripe_invoice_id')]
    public ?string $stripeInvoiceId;

    /**
     *
     * @var ?string $memo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('memo')]
    public ?string $memo;

    /**
     *
     * @var ?string $poNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('po_number')]
    public ?string $poNumber;

    /**
     *
     * @var ?LocalDate $dueDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('due_date')]
    public ?LocalDate $dueDate;

    /**
     *
     * @var ?string $onBehalfOfLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('on_behalf_of_label')]
    public ?string $onBehalfOfLabel;

    /**
     *
     * @var ?string $discountLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_label')]
    public ?string $discountLabel;

    /**
     *
     * @var ?string $stripeHostedInvoiceUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('stripe_hosted_invoice_url')]
    public ?string $stripeHostedInvoiceUrl;

    /**
     *
     * @var ?string $invoicePdfUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoice_pdf_url')]
    public ?string $invoicePdfUrl;

    /**
     *
     * @var ?string $checkoutLink
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('checkout_link')]
    public ?string $checkoutLink;

    /**
     * $userMetadata
     *
     * @var ?array<string, mixed> $userMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('user_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    public ?array $userMetadata;

    /**
     *
     * @var ?string $orderId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('order_id')]
    public ?string $orderId;

    /**
     * $lineItems
     *
     * @var ?array<ClientInvoiceLineItemSchema> $lineItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('line_items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Spaire\Models\Components\ClientInvoiceLineItemSchema>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $lineItems = null;

    /**
     * @param  string  $id
     * @param  \DateTime  $createdAt
     * @param  string  $organizationId
     * @param  string  $customerId
     * @param  ClientInvoiceStatus  $status
     * @param  string  $currency
     * @param  int  $subtotalAmount
     * @param  int  $discountAmount
     * @param  int  $taxAmount
     * @param  int  $totalAmount
     * @param  bool  $includePaymentLink
     * @param  bool  $showLogo
     * @param  bool  $showMorAttribution
     * @param  ?\DateTime  $modifiedAt
     * @param  ?string  $stripeInvoiceId
     * @param  ?string  $memo
     * @param  ?string  $poNumber
     * @param  ?LocalDate  $dueDate
     * @param  ?string  $onBehalfOfLabel
     * @param  ?string  $discountLabel
     * @param  ?string  $stripeHostedInvoiceUrl
     * @param  ?string  $invoicePdfUrl
     * @param  ?string  $checkoutLink
     * @param  ?array<string, mixed>  $userMetadata
     * @param  ?string  $orderId
     * @param  ?array<ClientInvoiceLineItemSchema>  $lineItems
     * @phpstan-pure
     */
    public function __construct(string $id, \DateTime $createdAt, string $organizationId, string $customerId, ClientInvoiceStatus $status, string $currency, int $subtotalAmount, int $discountAmount, int $taxAmount, int $totalAmount, bool $includePaymentLink, bool $showLogo, bool $showMorAttribution, ?\DateTime $modifiedAt = null, ?string $stripeInvoiceId = null, ?string $memo = null, ?string $poNumber = null, ?LocalDate $dueDate = null, ?string $onBehalfOfLabel = null, ?string $discountLabel = null, ?string $stripeHostedInvoiceUrl = null, ?string $invoicePdfUrl = null, ?string $checkoutLink = null, ?array $userMetadata = null, ?string $orderId = null, ?array $lineItems = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->organizationId = $organizationId;
        $this->customerId = $customerId;
        $this->status = $status;
        $this->currency = $currency;
        $this->subtotalAmount = $subtotalAmount;
        $this->discountAmount = $discountAmount;
        $this->taxAmount = $taxAmount;
        $this->totalAmount = $totalAmount;
        $this->includePaymentLink = $includePaymentLink;
        $this->showLogo = $showLogo;
        $this->showMorAttribution = $showMorAttribution;
        $this->modifiedAt = $modifiedAt;
        $this->stripeInvoiceId = $stripeInvoiceId;
        $this->memo = $memo;
        $this->poNumber = $poNumber;
        $this->dueDate = $dueDate;
        $this->onBehalfOfLabel = $onBehalfOfLabel;
        $this->discountLabel = $discountLabel;
        $this->stripeHostedInvoiceUrl = $stripeHostedInvoiceUrl;
        $this->invoicePdfUrl = $invoicePdfUrl;
        $this->checkoutLink = $checkoutLink;
        $this->userMetadata = $userMetadata;
        $this->orderId = $orderId;
        $this->lineItems = $lineItems;
    }
}