<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


enum ClientInvoiceSortProperty: string
{
    case CreatedAt = 'created_at';
    case MinusCreatedAt = '-created_at';
    case Status = 'status';
    case MinusStatus = '-status';
    case TotalAmount = 'total_amount';
    case MinusTotalAmount = '-total_amount';
    case DueDate = 'due_date';
    case MinusDueDate = '-due_date';
}
