<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;

use Brick\DateTime\LocalDate;
class ClientInvoiceCreate
{
    /**
     * ID of the Spaire customer to invoice.
     *
     * @var string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    public string $customerId;

    /**
     * ISO 4217 currency code (e.g. 'usd').
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * Invoice line items. At least one required.
     *
     * @var array<ClientInvoiceLineItemCreate> $lineItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('line_items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Spaire\Models\Components\ClientInvoiceLineItemCreate>')]
    public array $lineItems;

    /**
     * Payment due date. Determines days_until_due on the Stripe invoice.
     *
     * @var ?LocalDate $dueDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('due_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $dueDate = null;

    /**
     * Internal memo / invoice description.
     *
     * @var ?string $memo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('memo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $memo = null;

    /**
     * Purchase order number.
     *
     * @var ?string $poNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('po_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $poNumber = null;

    /**
     * Name shown in 'on behalf of' display on the invoice. Defaults to the organization name.
     *
     * @var ?string $onBehalfOfLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('on_behalf_of_label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $onBehalfOfLabel = null;

    /**
     * Label shown for the discount line on the invoice (e.g. 'Promo code').
     *
     * @var ?string $discountLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $discountLabel = null;

    /**
     * Arbitrary key-value metadata to attach to the invoice.
     *
     * @var ?array<string, mixed> $userMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('user_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $userMetadata = null;

    /**
     * Flat discount amount in the smallest currency unit (e.g. cents). Applied before tax.
     *
     * @var ?int $discountAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $discountAmount = null;

    /**
     * Whether to include a hosted payment link in the invoice email.
     *
     * @var ?bool $includePaymentLink
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('include_payment_link')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $includePaymentLink = null;

    /**
     * @param  string  $customerId
     * @param  string  $currency
     * @param  array<ClientInvoiceLineItemCreate>  $lineItems
     * @param  ?int  $discountAmount
     * @param  ?bool  $includePaymentLink
     * @param  ?LocalDate  $dueDate
     * @param  ?string  $memo
     * @param  ?string  $poNumber
     * @param  ?string  $onBehalfOfLabel
     * @param  ?string  $discountLabel
     * @param  ?array<string, mixed>  $userMetadata
     * @phpstan-pure
     */
    public function __construct(string $customerId, string $currency, array $lineItems, ?LocalDate $dueDate = null, ?string $memo = null, ?string $poNumber = null, ?string $onBehalfOfLabel = null, ?string $discountLabel = null, ?array $userMetadata = null, ?int $discountAmount = 0, ?bool $includePaymentLink = true)
    {
        $this->customerId = $customerId;
        $this->currency = $currency;
        $this->lineItems = $lineItems;
        $this->dueDate = $dueDate;
        $this->memo = $memo;
        $this->poNumber = $poNumber;
        $this->onBehalfOfLabel = $onBehalfOfLabel;
        $this->discountLabel = $discountLabel;
        $this->userMetadata = $userMetadata;
        $this->discountAmount = $discountAmount;
        $this->includePaymentLink = $includePaymentLink;
    }
}