<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;

use Brick\DateTime\LocalDate;
/** ClientInvoicePreviewRequest - Request body for generating a real-time PDF preview without persisting. */
class ClientInvoicePreviewRequest
{
    /**
     * Organization ID.
     *
     * @var string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public string $organizationId;

    /**
     * ISO 4217 currency code.
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * Invoice line items.
     *
     * @var array<ClientInvoiceLineItemPreview> $lineItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('line_items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Spaire\Models\Components\ClientInvoiceLineItemPreview>')]
    public array $lineItems;

    /**
     * Optional customer ID to pull name/address from.
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     *
     * @var ?LocalDate $dueDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('due_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $dueDate = null;

    /**
     *
     * @var ?string $memo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('memo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $memo = null;

    /**
     *
     * @var ?string $poNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('po_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $poNumber = null;

    /**
     *
     * @var ?string $onBehalfOfLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('on_behalf_of_label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $onBehalfOfLabel = null;

    /**
     *
     * @var ?string $discountLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $discountLabel = null;

    /**
     *
     * @var ?string $checkoutLinkUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('checkout_link_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $checkoutLinkUrl = null;

    /**
     *
     * @var ?string $billingName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingName = null;

    /**
     *
     * @var ?string $billingLine1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_line1')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingLine1 = null;

    /**
     *
     * @var ?string $billingLine2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_line2')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingLine2 = null;

    /**
     *
     * @var ?string $billingCity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingCity = null;

    /**
     *
     * @var ?string $billingState
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingState = null;

    /**
     *
     * @var ?string $billingPostalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_postal_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingPostalCode = null;

    /**
     *
     * @var ?string $billingCountry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_country')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingCountry = null;

    /**
     *
     * @var ?int $discountAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $discountAmount = null;

    /**
     *
     * @var ?bool $includePaymentLink
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('include_payment_link')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $includePaymentLink = null;

    /**
     * Whether to show the organization logo on the PDF.
     *
     * @var ?bool $showLogo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('show_logo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $showLogo = null;

    /**
     * Whether to show 'via spaire' label under the logo.
     *
     * @var ?bool $showMorAttribution
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('show_mor_attribution')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $showMorAttribution = null;

    /**
     * @param  string  $organizationId
     * @param  string  $currency
     * @param  array<ClientInvoiceLineItemPreview>  $lineItems
     * @param  ?int  $discountAmount
     * @param  ?bool  $includePaymentLink
     * @param  ?bool  $showLogo
     * @param  ?bool  $showMorAttribution
     * @param  ?string  $customerId
     * @param  ?LocalDate  $dueDate
     * @param  ?string  $memo
     * @param  ?string  $poNumber
     * @param  ?string  $onBehalfOfLabel
     * @param  ?string  $discountLabel
     * @param  ?string  $checkoutLinkUrl
     * @param  ?string  $billingName
     * @param  ?string  $billingLine1
     * @param  ?string  $billingLine2
     * @param  ?string  $billingCity
     * @param  ?string  $billingState
     * @param  ?string  $billingPostalCode
     * @param  ?string  $billingCountry
     * @phpstan-pure
     */
    public function __construct(string $organizationId, string $currency, array $lineItems, ?string $customerId = null, ?LocalDate $dueDate = null, ?string $memo = null, ?string $poNumber = null, ?string $onBehalfOfLabel = null, ?string $discountLabel = null, ?string $checkoutLinkUrl = null, ?string $billingName = null, ?string $billingLine1 = null, ?string $billingLine2 = null, ?string $billingCity = null, ?string $billingState = null, ?string $billingPostalCode = null, ?string $billingCountry = null, ?int $discountAmount = 0, ?bool $includePaymentLink = true, ?bool $showLogo = true, ?bool $showMorAttribution = true)
    {
        $this->organizationId = $organizationId;
        $this->currency = $currency;
        $this->lineItems = $lineItems;
        $this->customerId = $customerId;
        $this->dueDate = $dueDate;
        $this->memo = $memo;
        $this->poNumber = $poNumber;
        $this->onBehalfOfLabel = $onBehalfOfLabel;
        $this->discountLabel = $discountLabel;
        $this->checkoutLinkUrl = $checkoutLinkUrl;
        $this->billingName = $billingName;
        $this->billingLine1 = $billingLine1;
        $this->billingLine2 = $billingLine2;
        $this->billingCity = $billingCity;
        $this->billingState = $billingState;
        $this->billingPostalCode = $billingPostalCode;
        $this->billingCountry = $billingCountry;
        $this->discountAmount = $discountAmount;
        $this->includePaymentLink = $includePaymentLink;
        $this->showLogo = $showLogo;
        $this->showMorAttribution = $showMorAttribution;
    }
}