<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


class ClientInvoiceLineItemSchema
{
    /**
     * The ID of the object.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Creation timestamp of the object.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $clientInvoiceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('client_invoice_id')]
    public string $clientInvoiceId;

    /**
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     *
     * @var int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    public int $quantity;

    /**
     *
     * @var int $unitAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unit_amount')]
    public int $unitAmount;

    /**
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     *
     * @var int $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public int $amount;

    /**
     *
     * @var int $taxAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_amount')]
    public int $taxAmount;

    /**
     * Last modification timestamp of the object.
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     *
     * @var ?string $stripeInvoiceItemId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('stripe_invoice_item_id')]
    public ?string $stripeInvoiceItemId;

    /**
     * @param  string  $id
     * @param  \DateTime  $createdAt
     * @param  string  $clientInvoiceId
     * @param  string  $description
     * @param  int  $quantity
     * @param  int  $unitAmount
     * @param  string  $currency
     * @param  int  $amount
     * @param  int  $taxAmount
     * @param  ?\DateTime  $modifiedAt
     * @param  ?string  $stripeInvoiceItemId
     * @phpstan-pure
     */
    public function __construct(string $id, \DateTime $createdAt, string $clientInvoiceId, string $description, int $quantity, int $unitAmount, string $currency, int $amount, int $taxAmount, ?\DateTime $modifiedAt = null, ?string $stripeInvoiceItemId = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->clientInvoiceId = $clientInvoiceId;
        $this->description = $description;
        $this->quantity = $quantity;
        $this->unitAmount = $unitAmount;
        $this->currency = $currency;
        $this->amount = $amount;
        $this->taxAmount = $taxAmount;
        $this->modifiedAt = $modifiedAt;
        $this->stripeInvoiceItemId = $stripeInvoiceItemId;
    }
}