<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


enum EventSortProperty: string
{
    case Timestamp = 'timestamp';
    case MinusTimestamp = '-timestamp';
}
