<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


enum EventSource: string
{
    case System = 'system';
    case User = 'user';
}
