<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


class Filter
{
    /**
     *
     * @var FilterConjunction $conjunction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conjunction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\FilterConjunction')]
    public FilterConjunction $conjunction;

    /**
     * $clauses
     *
     * @var array<FilterClause|Filter> $clauses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clauses')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Spaire\Models\Components\FilterClause|\Spaire\Models\Components\Filter>')]
    public array $clauses;

    /**
     * @param  FilterConjunction  $conjunction
     * @param  array<FilterClause|Filter>  $clauses
     * @phpstan-pure
     */
    public function __construct(FilterConjunction $conjunction, array $clauses)
    {
        $this->conjunction = $conjunction;
        $this->clauses = $clauses;
    }
}