<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


class ListResourceWebhookEndpoint
{
    /**
     * $items
     *
     * @var array<\Spaire\Models\Components\WebhookEndpoint> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Spaire\Models\Components\WebhookEndpoint>')]
    public array $items;

    /**
     *
     * @var \Spaire\Models\Components\Pagination $pagination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pagination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\Pagination')]
    public Pagination $pagination;

    /**
     * @param  array<\Spaire\Models\Components\WebhookEndpoint>  $items
     * @param  \Spaire\Models\Components\Pagination  $pagination
     * @phpstan-pure
     */
    public function __construct(array $items, Pagination $pagination)
    {
        $this->items = $items;
        $this->pagination = $pagination;
    }
}