<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


class ListResourceWithCursorPaginationEvent
{
    /**
     * $items
     *
     * @var array<MeterCreditEvent|MeterResetEvent|BenefitGrantedEvent|BenefitCycledEvent|BenefitUpdatedEvent|BenefitRevokedEvent|SubscriptionCreatedEvent|SubscriptionCycledEvent|SubscriptionCanceledEvent|SubscriptionRevokedEvent|SubscriptionUncanceledEvent|SubscriptionProductUpdatedEvent|SubscriptionSeatsUpdatedEvent|SubscriptionBillingPeriodUpdatedEvent|OrderPaidEvent|OrderRefundedEvent|CheckoutCreatedEvent|CustomerCreatedEvent|CustomerUpdatedEvent|CustomerDeletedEvent|BalanceOrderEvent|BalanceCreditOrderEvent|BalanceRefundEvent|BalanceRefundReversalEvent|BalanceDisputeEvent|BalanceDisputeReversalEvent|UserEvent> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Spaire\Models\Components\MeterCreditEvent|\Spaire\Models\Components\MeterResetEvent|\Spaire\Models\Components\BenefitGrantedEvent|\Spaire\Models\Components\BenefitCycledEvent|\Spaire\Models\Components\BenefitUpdatedEvent|\Spaire\Models\Components\BenefitRevokedEvent|\Spaire\Models\Components\SubscriptionCreatedEvent|\Spaire\Models\Components\SubscriptionCycledEvent|\Spaire\Models\Components\SubscriptionCanceledEvent|\Spaire\Models\Components\SubscriptionRevokedEvent|\Spaire\Models\Components\SubscriptionUncanceledEvent|\Spaire\Models\Components\SubscriptionProductUpdatedEvent|\Spaire\Models\Components\SubscriptionSeatsUpdatedEvent|\Spaire\Models\Components\SubscriptionBillingPeriodUpdatedEvent|\Spaire\Models\Components\OrderPaidEvent|\Spaire\Models\Components\OrderRefundedEvent|\Spaire\Models\Components\CheckoutCreatedEvent|\Spaire\Models\Components\CustomerCreatedEvent|\Spaire\Models\Components\CustomerUpdatedEvent|\Spaire\Models\Components\CustomerDeletedEvent|\Spaire\Models\Components\BalanceOrderEvent|\Spaire\Models\Components\BalanceCreditOrderEvent|\Spaire\Models\Components\BalanceRefundEvent|\Spaire\Models\Components\BalanceRefundReversalEvent|\Spaire\Models\Components\BalanceDisputeEvent|\Spaire\Models\Components\BalanceDisputeReversalEvent|\Spaire\Models\Components\UserEvent>')]
    public array $items;

    /**
     *
     * @var CursorPagination $pagination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pagination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\CursorPagination')]
    public CursorPagination $pagination;

    /**
     * @param  array<MeterCreditEvent|MeterResetEvent|BenefitGrantedEvent|BenefitCycledEvent|BenefitUpdatedEvent|BenefitRevokedEvent|SubscriptionCreatedEvent|SubscriptionCycledEvent|SubscriptionCanceledEvent|SubscriptionRevokedEvent|SubscriptionUncanceledEvent|SubscriptionProductUpdatedEvent|SubscriptionSeatsUpdatedEvent|SubscriptionBillingPeriodUpdatedEvent|OrderPaidEvent|OrderRefundedEvent|CheckoutCreatedEvent|CustomerCreatedEvent|CustomerUpdatedEvent|CustomerDeletedEvent|BalanceOrderEvent|BalanceCreditOrderEvent|BalanceRefundEvent|BalanceRefundReversalEvent|BalanceDisputeEvent|BalanceDisputeReversalEvent|UserEvent>  $items
     * @param  CursorPagination  $pagination
     * @phpstan-pure
     */
    public function __construct(array $items, CursorPagination $pagination)
    {
        $this->items = $items;
        $this->pagination = $pagination;
    }
}