<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


class OrganizationStorefrontSettings
{
    /**
     * Skill/expertise tags displayed on the profile
     *
     * @var ?array<string> $skills
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('skills')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $skills = null;

    /**
     * Languages spoken
     *
     * @var ?array<string> $languages
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('languages')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $languages = null;

    /**
     * Product IDs to feature on the storefront (empty = show all)
     *
     * @var ?array<string> $featuredProductIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('featured_product_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $featuredProductIds = null;

    /**
     * URL of the storefront header/banner image
     *
     * @var ?string $headerImageUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('header_image_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $headerImageUrl = null;

    /**
     * Storefront description
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Profile title (e.g. Designer, 3D Artist)
     *
     * @var ?string $profileTitle
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile_title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $profileTitle = null;

    /**
     * Whether the storefront is enabled
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * Show the storefront header/banner
     *
     * @var ?bool $showHeader
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('show_header')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $showHeader = null;

    /**
     * Show the organization logo
     *
     * @var ?bool $showLogo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('show_logo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $showLogo = null;

    /**
     * Show the organization name
     *
     * @var ?bool $showName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('show_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $showName = null;

    /**
     * Show the storefront description
     *
     * @var ?bool $showDescription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('show_description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $showDescription = null;

    /**
     * Product thumbnail size
     *
     * @var ?\Spaire\Models\Components\ThumbnailSize $thumbnailSize
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('thumbnail_size')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\ThumbnailSize|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ThumbnailSize $thumbnailSize = null;

    /**
     * Show product details (name, price)
     *
     * @var ?bool $showProductDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('show_product_details')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $showProductDetails = null;

    /**
     * Show 'Available for work' badge on the profile
     *
     * @var ?bool $availableForWork
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('available_for_work')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $availableForWork = null;

    /**
     * @param  ?bool  $enabled
     * @param  ?bool  $showHeader
     * @param  ?bool  $showLogo
     * @param  ?bool  $showName
     * @param  ?bool  $showDescription
     * @param  ?\Spaire\Models\Components\ThumbnailSize  $thumbnailSize
     * @param  ?bool  $showProductDetails
     * @param  ?array<string>  $skills
     * @param  ?array<string>  $languages
     * @param  ?bool  $availableForWork
     * @param  ?array<string>  $featuredProductIds
     * @param  ?string  $headerImageUrl
     * @param  ?string  $description
     * @param  ?string  $profileTitle
     * @phpstan-pure
     */
    public function __construct(?array $skills = null, ?array $languages = null, ?array $featuredProductIds = null, ?string $headerImageUrl = null, ?string $description = null, ?string $profileTitle = null, ?bool $enabled = false, ?bool $showHeader = true, ?bool $showLogo = true, ?bool $showName = true, ?bool $showDescription = true, ?ThumbnailSize $thumbnailSize = ThumbnailSize::Medium, ?bool $showProductDetails = true, ?bool $availableForWork = false)
    {
        $this->skills = $skills;
        $this->languages = $languages;
        $this->featuredProductIds = $featuredProductIds;
        $this->headerImageUrl = $headerImageUrl;
        $this->description = $description;
        $this->profileTitle = $profileTitle;
        $this->enabled = $enabled;
        $this->showHeader = $showHeader;
        $this->showLogo = $showLogo;
        $this->showName = $showName;
        $this->showDescription = $showDescription;
        $this->thumbnailSize = $thumbnailSize;
        $this->showProductDetails = $showProductDetails;
        $this->availableForWork = $availableForWork;
    }
}