<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


class OrganizationFeatureSettings
{
    /**
     * If this organization has issue funding enabled
     *
     * @var ?bool $issueFundingEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('issue_funding_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $issueFundingEnabled = null;

    /**
     * If this organization has seat-based pricing enabled
     *
     * @var ?bool $seatBasedPricingEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('seat_based_pricing_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $seatBasedPricingEnabled = null;

    /**
     * If this organization has RevOps enabled
     *
     * @var ?bool $revopsEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('revops_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $revopsEnabled = null;

    /**
     * If this organization has Wallets enabled
     *
     * @var ?bool $walletsEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('wallets_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $walletsEnabled = null;

    /**
     * If this organization has the Member model enabled
     *
     * @var ?bool $memberModelEnabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('member_model_enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $memberModelEnabled = null;

    /**
     * If this organization reads from Tinybird
     *
     * @var ?bool $tinybirdRead
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tinybird_read')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $tinybirdRead = null;

    /**
     * If this organization compares Tinybird results with database
     *
     * @var ?bool $tinybirdCompare
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tinybird_compare')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $tinybirdCompare = null;

    /**
     * If this organization has unlocked the Startup Stack perks by completing their first sale
     *
     * @var ?bool $perksUnlocked
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('perks_unlocked')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $perksUnlocked = null;

    /**
     * @param  ?bool  $issueFundingEnabled
     * @param  ?bool  $seatBasedPricingEnabled
     * @param  ?bool  $revopsEnabled
     * @param  ?bool  $walletsEnabled
     * @param  ?bool  $memberModelEnabled
     * @param  ?bool  $tinybirdRead
     * @param  ?bool  $tinybirdCompare
     * @param  ?bool  $perksUnlocked
     * @phpstan-pure
     */
    public function __construct(?bool $issueFundingEnabled = false, ?bool $seatBasedPricingEnabled = false, ?bool $revopsEnabled = false, ?bool $walletsEnabled = false, ?bool $memberModelEnabled = false, ?bool $tinybirdRead = false, ?bool $tinybirdCompare = false, ?bool $perksUnlocked = false)
    {
        $this->issueFundingEnabled = $issueFundingEnabled;
        $this->seatBasedPricingEnabled = $seatBasedPricingEnabled;
        $this->revopsEnabled = $revopsEnabled;
        $this->walletsEnabled = $walletsEnabled;
        $this->memberModelEnabled = $memberModelEnabled;
        $this->tinybirdRead = $tinybirdRead;
        $this->tinybirdCompare = $tinybirdCompare;
        $this->perksUnlocked = $perksUnlocked;
    }
}