<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


class OrganizationCreate
{
    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $slug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('slug')]
    public string $slug;

    /**
     *
     * @var ?\Spaire\Models\Components\TaxBehaviorOption $defaultTaxBehavior
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('default_tax_behavior')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\TaxBehaviorOption|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TaxBehaviorOption $defaultTaxBehavior = null;

    /**
     *
     * @var ?string $avatarUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('avatar_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $avatarUrl = null;

    /**
     * Public support email.
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     * Official website of the organization.
     *
     * @var ?string $website
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('website')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $website = null;

    /**
     * Link to social profiles.
     *
     * @var ?array<\Spaire\Models\Components\OrganizationSocialLink> $socials
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('socials')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Spaire\Models\Components\OrganizationSocialLink>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $socials = null;

    /**
     * Additional, private, business details Spaire needs about active organizations for compliance (KYC).
     *
     * @var ?\Spaire\Models\Components\OrganizationDetails $details
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('details')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\OrganizationDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrganizationDetails $details = null;

    /**
     *
     * @var ?\Spaire\Models\Components\OrganizationFeatureSettings $featureSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feature_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\OrganizationFeatureSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrganizationFeatureSettings $featureSettings = null;

    /**
     *
     * @var ?\Spaire\Models\Components\OrganizationSubscriptionSettings $subscriptionSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\OrganizationSubscriptionSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrganizationSubscriptionSettings $subscriptionSettings = null;

    /**
     *
     * @var ?\Spaire\Models\Components\OrganizationNotificationSettings $notificationSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('notification_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\OrganizationNotificationSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrganizationNotificationSettings $notificationSettings = null;

    /**
     *
     * @var ?\Spaire\Models\Components\OrganizationCustomerEmailSettings $customerEmailSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_email_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\OrganizationCustomerEmailSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrganizationCustomerEmailSettings $customerEmailSettings = null;

    /**
     *
     * @var ?\Spaire\Models\Components\OrganizationCustomerPortalSettings $customerPortalSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_portal_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\OrganizationCustomerPortalSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrganizationCustomerPortalSettings $customerPortalSettings = null;

    /**
     *
     * @var ?\Spaire\Models\Components\OrganizationStorefrontSettings $storefrontSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('storefront_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\OrganizationStorefrontSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OrganizationStorefrontSettings $storefrontSettings = null;

    /**
     * @param  string  $name
     * @param  string  $slug
     * @param  ?\Spaire\Models\Components\TaxBehaviorOption  $defaultTaxBehavior
     * @param  ?string  $avatarUrl
     * @param  ?string  $email
     * @param  ?string  $website
     * @param  ?array<\Spaire\Models\Components\OrganizationSocialLink>  $socials
     * @param  ?\Spaire\Models\Components\OrganizationDetails  $details
     * @param  ?\Spaire\Models\Components\OrganizationFeatureSettings  $featureSettings
     * @param  ?\Spaire\Models\Components\OrganizationSubscriptionSettings  $subscriptionSettings
     * @param  ?\Spaire\Models\Components\OrganizationNotificationSettings  $notificationSettings
     * @param  ?\Spaire\Models\Components\OrganizationCustomerEmailSettings  $customerEmailSettings
     * @param  ?\Spaire\Models\Components\OrganizationCustomerPortalSettings  $customerPortalSettings
     * @param  ?\Spaire\Models\Components\OrganizationStorefrontSettings  $storefrontSettings
     * @phpstan-pure
     */
    public function __construct(string $name, string $slug, ?TaxBehaviorOption $defaultTaxBehavior = null, ?string $avatarUrl = null, ?string $email = null, ?string $website = null, ?array $socials = null, ?OrganizationDetails $details = null, ?OrganizationFeatureSettings $featureSettings = null, ?OrganizationSubscriptionSettings $subscriptionSettings = null, ?OrganizationNotificationSettings $notificationSettings = null, ?OrganizationCustomerEmailSettings $customerEmailSettings = null, ?OrganizationCustomerPortalSettings $customerPortalSettings = null, ?OrganizationStorefrontSettings $storefrontSettings = null)
    {
        $this->name = $name;
        $this->slug = $slug;
        $this->defaultTaxBehavior = $defaultTaxBehavior;
        $this->avatarUrl = $avatarUrl;
        $this->email = $email;
        $this->website = $website;
        $this->socials = $socials;
        $this->details = $details;
        $this->featureSettings = $featureSettings;
        $this->subscriptionSettings = $subscriptionSettings;
        $this->notificationSettings = $notificationSettings;
        $this->customerEmailSettings = $customerEmailSettings;
        $this->customerPortalSettings = $customerPortalSettings;
        $this->storefrontSettings = $storefrontSettings;
    }
}