<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


/** ProductPriceCustom - A pay-what-you-want price for a product. */
class ProductPriceCustom
{
    /**
     * Creation timestamp of the object.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * The ID of the price.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var \Spaire\Models\Components\ProductPriceSource $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\ProductPriceSource')]
    public ProductPriceSource $source;

    /**
     *
     * @var \Spaire\Models\Components\PresentmentCurrency $priceCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price_currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\PresentmentCurrency')]
    public PresentmentCurrency $priceCurrency;

    /**
     * Whether the price is archived and no longer available.
     *
     * @var bool $isArchived
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_archived')]
    public bool $isArchived;

    /**
     * The ID of the product owning the price.
     *
     * @var string $productId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_id')]
    public string $productId;

    /**
     *
     * @var \Spaire\Models\Components\ProductPriceType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\ProductPriceType')]
    public ProductPriceType $type;

    /**
     * The minimum amount the customer can pay. If 0, the price is 'free or pay what you want'. Defaults to 50 cents.
     *
     * @var int $minimumAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('minimum_amount')]
    public int $minimumAmount;

    /**
     * Last modification timestamp of the object.
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     * The tax behavior of the price. If null, it defaults to the organization's default tax behavior.
     *
     * @var ?\Spaire\Models\Components\TaxBehaviorOption $taxBehavior
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_behavior')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\TaxBehaviorOption|null')]
    public ?TaxBehaviorOption $taxBehavior;

    /**
     *
     * @var ?\Spaire\Models\Components\SubscriptionRecurringInterval $recurringInterval
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurring_interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\SubscriptionRecurringInterval|null')]
    public ?SubscriptionRecurringInterval $recurringInterval;

    /**
     * The maximum amount the customer can pay.
     *
     * @var ?int $maximumAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maximum_amount')]
    public ?int $maximumAmount;

    /**
     * The initial amount shown to the customer.
     *
     * @var ?int $presetAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('preset_amount')]
    public ?int $presetAmount;

    /**
     *
     * @var string $amountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_type')]
    public string $amountType;

    /**
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  \Spaire\Models\Components\ProductPriceSource  $source
     * @param  string  $amountType
     * @param  \Spaire\Models\Components\PresentmentCurrency  $priceCurrency
     * @param  bool  $isArchived
     * @param  string  $productId
     * @param  \Spaire\Models\Components\ProductPriceType  $type
     * @param  int  $minimumAmount
     * @param  ?\DateTime  $modifiedAt
     * @param  ?\Spaire\Models\Components\TaxBehaviorOption  $taxBehavior
     * @param  ?\Spaire\Models\Components\SubscriptionRecurringInterval  $recurringInterval
     * @param  ?int  $maximumAmount
     * @param  ?int  $presetAmount
     * @phpstan-pure
     */
    public function __construct(\DateTime $createdAt, string $id, ProductPriceSource $source, PresentmentCurrency $priceCurrency, bool $isArchived, string $productId, ProductPriceType $type, int $minimumAmount, ?\DateTime $modifiedAt = null, ?TaxBehaviorOption $taxBehavior = null, ?SubscriptionRecurringInterval $recurringInterval = null, ?int $maximumAmount = null, ?int $presetAmount = null, string $amountType = 'custom')
    {
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->source = $source;
        $this->priceCurrency = $priceCurrency;
        $this->isArchived = $isArchived;
        $this->productId = $productId;
        $this->type = $type;
        $this->minimumAmount = $minimumAmount;
        $this->modifiedAt = $modifiedAt;
        $this->taxBehavior = $taxBehavior;
        $this->recurringInterval = $recurringInterval;
        $this->maximumAmount = $maximumAmount;
        $this->presetAmount = $presetAmount;
        $this->amountType = $amountType;
    }
}