<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


/** ProductTaxPreviewResponse - Tax preview result for a product price. */
class ProductTaxPreviewResponse
{
    /**
     *
     * @var int $subtotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtotal')]
    public int $subtotal;

    /**
     *
     * @var int $taxAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_amount')]
    public int $taxAmount;

    /**
     *
     * @var int $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public int $total;

    /**
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     *
     * @var int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    public int $quantity;

    /**
     *
     * @var ?TaxRatePreview $taxRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_rate')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\TaxRatePreview|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TaxRatePreview $taxRate = null;

    /**
     *
     * @var ?string $taxabilityReason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('taxability_reason')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxabilityReason = null;

    /**
     * @param  int  $subtotal
     * @param  int  $taxAmount
     * @param  int  $total
     * @param  string  $currency
     * @param  int  $quantity
     * @param  ?TaxRatePreview  $taxRate
     * @param  ?string  $taxabilityReason
     * @phpstan-pure
     */
    public function __construct(int $subtotal, int $taxAmount, int $total, string $currency, int $quantity, ?TaxRatePreview $taxRate = null, ?string $taxabilityReason = null)
    {
        $this->subtotal = $subtotal;
        $this->taxAmount = $taxAmount;
        $this->total = $total;
        $this->currency = $currency;
        $this->quantity = $quantity;
        $this->taxRate = $taxRate;
        $this->taxabilityReason = $taxabilityReason;
    }
}