<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


/** ProductPriceFixedCreate - Schema to create a fixed price. */
class ProductPriceFixedCreate
{
    /**
     * The price in cents.
     *
     * @var int $priceAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price_amount')]
    public int $priceAmount;

    /**
     *
     * @var ?\Spaire\Models\Components\PresentmentCurrency $priceCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price_currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\PresentmentCurrency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PresentmentCurrency $priceCurrency = null;

    /**
     * The tax behavior of the price. If not set, it will default to the organization's default tax behavior.
     *
     * @var ?\Spaire\Models\Components\TaxBehaviorOption $taxBehavior
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_behavior')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\TaxBehaviorOption|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TaxBehaviorOption $taxBehavior = null;

    /**
     *
     * @var string $amountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_type')]
    public string $amountType;

    /**
     * @param  string  $amountType
     * @param  int  $priceAmount
     * @param  ?\Spaire\Models\Components\PresentmentCurrency  $priceCurrency
     * @param  ?\Spaire\Models\Components\TaxBehaviorOption  $taxBehavior
     * @phpstan-pure
     */
    public function __construct(int $priceAmount, ?PresentmentCurrency $priceCurrency = null, ?TaxBehaviorOption $taxBehavior = null, string $amountType = 'fixed')
    {
        $this->priceAmount = $priceAmount;
        $this->priceCurrency = $priceCurrency;
        $this->taxBehavior = $taxBehavior;
        $this->amountType = $amountType;
    }
}