<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


/**
 * ProductPriceSeatBasedCreate - Schema to create a seat-based price with tiered pricing.
 *
 *
 * Supports volume pricing (all seats at matching tier's rate) and
 * graduated pricing (each tier's range priced independently).
 */
class ProductPriceSeatBasedCreate
{
    /**
     * List of pricing tiers for seat-based pricing.
     *
     *
     * The minimum and maximum seat limits are derived from the tiers:
     * - minimum_seats = first tier's min_seats
     * - maximum_seats = last tier's max_seats (None for unlimited)
     *
     * @var \Spaire\Models\Components\ProductPriceSeatTiersInput $seatTiers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('seat_tiers')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\ProductPriceSeatTiersInput')]
    public ProductPriceSeatTiersInput $seatTiers;

    /**
     *
     * @var ?\Spaire\Models\Components\PresentmentCurrency $priceCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price_currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\PresentmentCurrency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PresentmentCurrency $priceCurrency = null;

    /**
     * The tax behavior of the price. If not set, it will default to the organization's default tax behavior.
     *
     * @var ?\Spaire\Models\Components\TaxBehaviorOption $taxBehavior
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax_behavior')]
    #[\Speakeasy\Serializer\Annotation\Type('\Spaire\Models\Components\TaxBehaviorOption|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TaxBehaviorOption $taxBehavior = null;

    /**
     *
     * @var string $amountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_type')]
    public string $amountType;

    /**
     * @param  string  $amountType
     * @param  \Spaire\Models\Components\ProductPriceSeatTiersInput  $seatTiers
     * @param  ?\Spaire\Models\Components\PresentmentCurrency  $priceCurrency
     * @param  ?\Spaire\Models\Components\TaxBehaviorOption  $taxBehavior
     * @phpstan-pure
     */
    public function __construct(ProductPriceSeatTiersInput $seatTiers, ?PresentmentCurrency $priceCurrency = null, ?TaxBehaviorOption $taxBehavior = null, string $amountType = 'seat_based')
    {
        $this->seatTiers = $seatTiers;
        $this->priceCurrency = $priceCurrency;
        $this->taxBehavior = $taxBehavior;
        $this->amountType = $amountType;
    }
}