<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


/** ProductTaxPreviewRequest - Request body for previewing tax on a product price. */
class ProductTaxPreviewRequest
{
    /**
     * Amount in smallest currency unit (e.g. cents for USD).
     *
     * @var int $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public int $amount;

    /**
     * ISO 4217 currency code (e.g. 'usd').
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * ISO 3166-1 alpha-2 country code (e.g. 'AU').
     *
     * @var string $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    public string $country;

    /**
     * State/province code for US/CA (e.g. 'WA' or 'US-WA').
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     * Unit quantity for the preview calculation.
     *
     * @var ?int $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $quantity = null;

    /**
     * @param  int  $amount
     * @param  string  $currency
     * @param  string  $country
     * @param  ?int  $quantity
     * @param  ?string  $state
     * @phpstan-pure
     */
    public function __construct(int $amount, string $currency, string $country, ?string $state = null, ?int $quantity = 1)
    {
        $this->amount = $amount;
        $this->currency = $currency;
        $this->country = $country;
        $this->state = $state;
        $this->quantity = $quantity;
    }
}