<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


class S3FileCreateMultipart
{
    /**
     * $parts
     *
     * @var array<\Spaire\Models\Components\S3FileCreatePart> $parts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parts')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Spaire\Models\Components\S3FileCreatePart>')]
    public array $parts;

    /**
     * @param  array<\Spaire\Models\Components\S3FileCreatePart>  $parts
     * @phpstan-pure
     */
    public function __construct(array $parts)
    {
        $this->parts = $parts;
    }
}