<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


class TaxRatePreview
{
    /**
     *
     * @var string $displayName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('display_name')]
    public string $displayName;

    /**
     *
     * @var ?float $percentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('percentage')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $percentage = null;

    /**
     * @param  string  $displayName
     * @param  ?float  $percentage
     * @phpstan-pure
     */
    public function __construct(string $displayName, ?float $percentage = null)
    {
        $this->displayName = $displayName;
        $this->percentage = $percentage;
    }
}