<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire\Models\Components;


/** Product thumbnail size */
enum ThumbnailSize: string
{
    case Small = 'small';
    case Medium = 'medium';
    case Large = 'large';
}
