<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire;



class CustomerPortal
{
    private SDKConfiguration $sdkConfiguration;
    public SpaireBenefitGrants $benefitGrants;

    public SpaireCustomers $customers;

    public SpaireCustomerMeters $customerMeters;

    public Seats $seats;

    public CustomerSession $customerSession;

    public Downloadables $downloadables;

    public SpaireLicenseKeys $licenseKeys;

    public SpaireMembers $members;

    public SpaireOrders $orders;

    public SpaireOrganizations $organizations;

    public SpaireSubscriptions $subscriptions;

    public Wallets $wallets;

    /**
     * @param  SDKConfiguration  $sdkConfig
     */
    public function __construct(public SDKConfiguration $sdkConfig)
    {
        $this->sdkConfiguration = $sdkConfig;
        $this->benefitGrants = new SpaireBenefitGrants($this->sdkConfiguration);
        $this->customers = new SpaireCustomers($this->sdkConfiguration);
        $this->customerMeters = new SpaireCustomerMeters($this->sdkConfiguration);
        $this->seats = new Seats($this->sdkConfiguration);
        $this->customerSession = new CustomerSession($this->sdkConfiguration);
        $this->downloadables = new Downloadables($this->sdkConfiguration);
        $this->licenseKeys = new SpaireLicenseKeys($this->sdkConfiguration);
        $this->members = new SpaireMembers($this->sdkConfiguration);
        $this->orders = new SpaireOrders($this->sdkConfiguration);
        $this->organizations = new SpaireOrganizations($this->sdkConfiguration);
        $this->subscriptions = new SpaireSubscriptions($this->sdkConfiguration);
        $this->wallets = new Wallets($this->sdkConfiguration);
    }
    /**
     * @param  string  $baseUrl
     * @param  array<string, string>  $urlVariables
     *
     * @return string
     */
    public function getUrl(string $baseUrl, array $urlVariables): string
    {
        $serverDetails = $this->sdkConfiguration->getServerDetails();

        if ($baseUrl == null) {
            $baseUrl = $serverDetails->baseUrl;
        }

        if ($urlVariables == null) {
            $urlVariables = $serverDetails->options;
        }

        return Utils\Utils::templateUrl($baseUrl, $urlVariables);
    }

}