<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Spaire;

use Spaire\Utils\Retry;

/**
 * SpaireBuilder is used to configure and build an instance of the SDK.
 */
class SpaireBuilder
{
    public function __construct(
        private SDKConfiguration $sdkConfig = new SDKConfiguration(),
    ) {
    }

    /**
     * setClient allows setting a custom Guzzle client for the SDK to make requests with.
     *
     * @param  \GuzzleHttp\ClientInterface  $client
     * @return SpaireBuilder
     */
    public function setClient(\GuzzleHttp\ClientInterface $client): SpaireBuilder
    {
        $this->sdkConfig->client = $client;

        return $this;
    }

    /**
     * setSecurity is used to configure the security required for the SDK.
     *
     * @param  string  $accessToken
     * @return SpaireBuilder
     */
    public function setSecurity(string $accessToken): SpaireBuilder
    {
        $security = new Models\Components\Security(
            accessToken: $accessToken
        );
        $this->sdkConfig->securitySource = fn () => $security;

        return $this;
    }

    /**
     * setSecuritySource is usd to configure the security required for the SDK.
     * unlike setSecurity, setSecuritySource accepts a closure that will be called to retrieve the security information.
     *
     * @param  pure-Closure(): string  $securitySource
     * @return SpaireBuilder
     */
    public function setSecuritySource(\Closure $securitySource): SpaireBuilder
    {
        $this->sdkConfig->securitySource = fn () => new Models\Components\Security(accessToken: $securitySource());

        return $this;
    }

    /**
     * setServerUrl is used to configure the server URL for the SDK, and optionally template any parameters in the URL.
     *
     * @param  string  $serverUrl
     * @param  array<string, string>  $params
     * @return SpaireBuilder
     */
    public function setServerUrl(string $serverUrl, ?array $params = null): SpaireBuilder
    {
        $this->sdkConfig->serverUrl = Utils\Utils::templateUrl($serverUrl, $params);

        return $this;
    }

    /**
     * setServer is used to configure the server for the SDK
     *
     * @param  string  $server
     * @return SpaireBuilder
     */
    public function setServer(string $server): SpaireBuilder
    {
        $this->sdkConfig->server = $server;

        return $this;
    }

    public function setRetryConfig(Retry\RetryConfig $config): SpaireBuilder
    {
        $this->sdkConfig->retryConfig = $config;

        return $this;
    }

    /**
     * build is used to build the SDK with any of the configured options.
     *
     * @return Spaire
     */
    public function build(): Spaire
    {
        if ($this->sdkConfig->client === null) {
            $this->sdkConfig->client = new \GuzzleHttp\Client([
                'timeout' => 60,
            ]);
        }
        if ($this->sdkConfig->hasSecurity()) {
            $this->sdkConfig->client = Utils\Utils::configureSecurityClient($this->sdkConfig->client, $this->sdkConfig->getSecurity());
        }

        return new Spaire($this->sdkConfig);
    }
}